version: 1
sources:
  - name: chicago_taxi_trips
    database: bigquery-public-data
    schema: chicago_taxi_trips
    tables:
      - name: taxi_trips
  - name: google_sheets
    description: "Data"

  - name: tips_change_month_by_month
    database: shusobi-test
    schema: tips_change_month_by_month
    tables:
      - name: tips_change_month_by_month
        freshness: null
